<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoiceNumber }}</title>
    <style>
        body { font-family: Georgia, 'Times New Roman', serif; color: #1f2937; max-width: 720px; margin: 40px auto; padding: 0 24px; }
        h1 { font-size: 28px; margin: 0; }
        .muted { color: #6b7280; }
        .row { display: flex; justify-content: space-between; gap: 24px; margin-top: 32px; }
        table { width: 100%; border-collapse: collapse; margin-top: 32px; }
        th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #e5e7eb; }
        .total { font-size: 18px; font-weight: bold; }
        .actions { margin-top: 32px; display: flex; gap: 12px; }
        .btn { display: inline-block; padding: 10px 16px; background: #111827; color: #fff; text-decoration: none; border-radius: 6px; font-family: system-ui, sans-serif; font-size: 14px; }
        .btn-secondary { background: #fff; color: #111827; border: 1px solid #d1d5db; }
        @media print {
            .actions { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body>
    <div class="actions">
        <button class="btn" onclick="window.print()">Print / Save as PDF</button>
        <a class="btn btn-secondary" href="{{ route('invoices.download', $milestone) }}">Download HTML</a>
        <a class="btn btn-secondary" href="{{ route('projects.show', $project) }}">Back to project</a>
    </div>

    <header style="margin-top: 24px;">
        <h1>WorkVault Invoice</h1>
        <p class="muted">Invoice {{ $invoiceNumber }}</p>
    </header>

    <div class="row">
        <div>
            <p class="muted">Bill to</p>
            <p><strong>{{ $project->client->name }}</strong></p>
            @if ($project->client->profile?->company_name)
                <p>{{ $project->client->profile->company_name }}</p>
            @endif
            <p>{{ $project->client->email }}</p>
        </div>
        <div style="text-align: right;">
            <p class="muted">Paid to</p>
            <p><strong>{{ $project->freelancer?->name }}</strong></p>
            <p>{{ $project->freelancer?->email }}</p>
            <p class="muted" style="margin-top: 12px;">Date</p>
            <p>{{ ($transaction?->created_at ?? $milestone->approved_at ?? now())->format('M j, Y') }}</p>
        </div>
    </div>

    <p style="margin-top: 32px;"><span class="muted">Project:</span> {{ $project->title }}</p>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Milestone: {{ $milestone->title }}
                    @if ($milestone->submission_notes)
                        <div class="muted" style="margin-top: 6px; font-size: 13px;">{{ \Illuminate\Support\Str::limit($milestone->submission_notes, 160) }}</div>
                    @endif
                </td>
                <td>${{ number_format($milestone->amount, 2) }}</td>
            </tr>
            <tr>
                <td class="total">Total paid via escrow</td>
                <td class="total">${{ number_format($milestone->amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <p class="muted" style="margin-top: 40px; font-size: 13px;">
        This is a mock escrow invoice generated by WorkVault for project tracking purposes.
    </p>
</body>
</html>
